ecommers_project/cart_app/urls.py
from django.urls import path
from .import views

app_name='cart_app'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/', views.full_remove, name='full_remove'),

]

ecommers_project/ecommers_app/urls.py
from . import views
from django.urls import path, include
app_name='ecommers_app'
urlpatterns = [

    # path('',views.index,name='index')
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),

]

ecommers_project/ecommers_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommers/',include('ecommers_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart_app/',include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommers_project/search_app/urls.py
from django.urls import path
from .import views

app_name='search_app'

urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

ecommers_project/cart_app/models.py
from django.db import models
from ecommers_app.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    # def __str__(self):
    #     return self.product.price * self.quantity

    def  __str__(self):
        return '{}'.format(self.product)

ecommers_project/ecommers_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=300,unique=True)  #unique using the name consider only unque value
    # when a name is creted tha time , automaticaly url created using slug
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    # img are uploaded to 'categories'folder/directory
    image=models.ImageField(upload_to='category',blank=True)

    class Metta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('ecommers_app:product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

#product feild
class Product(models.Model):
    name = models.CharField(max_length=300, unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE) #cascade using the previous values delete and new add
    image= models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)
    # detail
    def get_url(self):
        return reverse('ecommers_app:prodCatdetail',args=[self.category.slug,self.slug])

    class Metta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

ecommers_project/search_app/models.py
from django.db import models

# Create your models here.

ecommers_project/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommers_app.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock :
           cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,quantity=1,cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

# cart page  pro remove one by one(minus) function
def cart_remove(request,product_id):
    cart= Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')

# delete pro in cart page
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommers_project/ecommers_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from ecommers_app.models import Category, Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
# def index(request):
#     return HttpResponse('hellooooooo')

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'product1':products})
# pro-->click-->prodetails
def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'kproduct':product})

ecommers_project/search_app/views.py
from django.shortcuts import render
from ecommers_app.models import Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    S_products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        S_products=Product.objects.all().filter(Q(name__contains=query) )
    return render(request,'search.html',{'query':query,'products':S_products})

ecommers_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<!--    style-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--     Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
<!--    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!--    font style-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hedvig+Letters+Serif:opsz@12..24&display=swap" rel="stylesheet">
<!--    end font-->
     <script src="https://kit.fontawesome.com/6a89adeb3f.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
      {% include 'header.html' %}
      {% include 'navbar.html' %}
       {% block content %}
       {% endblock %}
    </div>
{% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!--    <script src="{% static 'code.jquery.com/jquery-3.2.1.slim.min.js' %}" ></script>-->
<!--    <script src="{% static 'js/popper.min.js' %}" ></script>-->
<!--    <script src="{% static 'js/bootstrap.min.js' %}" ></script>-->

</body>
</html>

ecommers_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page. proceed to review your items and place the order
{% endblock %}
{% block title %}
    Cart- ES Company PVT LTD
{% endblock %}
{% block content %}
<!--empty cart-->
{% if not cart_items %}
  <div>
      <div class="text-center">
          <br>
          <h1 class="text-center my_title">
              Your Shopping Cart is empty
          </h1>
          <br>
          <p class="text-center">
              Please Click <a href="{% url 'ecommers_app:allProdCart' %}">Here</a>to continue shopping.
          </p>
      </div>
  </div>
{% else %}
  <div>
      <div class="text-center">
          <br>
          <h1 class="text-center my_title">
              Your Shopping Cart
          </h1>
          <br>
      </div>
  </div>
  <div class="row mx-auto">
      <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
          <table class="table my_custom_table">
                <thead class="my_custom_thead">
                  <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {% for cart_item in cart_items %}
                   <tr>
                      <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" width="100px;" height="100px;"></a>
                      </td>
                      <td class="text-left">
                         {{ cart_item.product.name }}
                       <br>
                         SKU: {{ cart_item.product.id }}
                       <br>
                         price :${{ cart_item.product.price }}
                       <br>
                         Qty : {{ cart_item.quantity }} x $ {{ cart_item }}
                      </td>
                      <td>
                        $ {{cart_item.sub_total}}
                      </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                      <td>
                        <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                           &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                           &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
                      </td>
                    {% else %}
                        <td>
                           &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                           &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
                        </td>
                    {% endif %}
                   </tr>
                 {% endfor %}
                </tbody>
          </table>
      </div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
           <table class="table my_custom_table">
                <thead class="my_custom_thead">
                    <tr>
                      <th>
                        Checkout
                      </th>
                    </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      Please review your shopping cart items before proceeding with the order payment.
                    </td>
                  </tr>
                <tr>
                    <td class="text-left">
                        Your Total is : <strong>{{ total }}</strong>
                    </td>
                </tr>
                </tbody>
           </table>
         <div class="mx-auto">
            <a href="{% url 'ecommers_app:allProdCat' %}" class="btn btn-secondary btr-block my_custom_button">Continue Shopping</a>
        </div>
      </div>
  </div>
{% endif %}
{% endblock %}

ecommers_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
         {{ category.description|truncatewords:155 }}
    {% else %}
         Welcome to ECS store where you can buys different items...
    {% endif %}
{% endblock %}
{% block title %}
   {% if category %}
     {{ category.name }} -ECS Store
   {% else %}
      See our New Collections - ECS Store
   {% endif %}
{% endblock %}

<!--CATEGORY FEILD-->

{% block content %}
<!--this categery is a var_name of c_page-->
   {% if category %}
      <div>
          <div class="row my_row_class">
              <div class="mx-auto">
               <p><a href="{% url 'ecommers_app:allProdCat' %}">Our Product Collections </a></p>
               </div>
          </div>
      </div>
  {% endif %}
  <div class="mx_auto">
      {% if category %}
           <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="500px" height="300px">
  </div>
    <br>
  <div>
     <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
  </div>
     {% else %}
        <div>
          <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our Products" width="1190px;" height="600px">
        </div>
         <br>
        <div>
            <h1 class="text-center my_title"><b>Our Products Collections </b></h1>
           <p class="text-justify">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.</p>
        </div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
<!--        here the product is the var_name of itrative vriable -->
        {% for kproduct in product1.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
          <div class="card text-center" style="min-width:18rem;">
              <a href="{{kproduct.get_url}}"><img class="card-img-top my-image" src="{{kproduct.image.url}}" alt="{{kproduct.name}}" width="300px" height="200px"></a>
          <div class="card-body">
              <h4><b>{{kproduct.name}}</b></h4>
              <p>${{kproduct.price}}</p>
          </div>
          </div>
        </div>
        {% endfor %}
    </div>
<!--    page number display-->
    <div class="mx-auto">
        {% if product1.paginator.num_pages > 1 %}
          <hr>
          <div class="text-center">
            {% for pg in product1.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product1.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
          </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommers_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; ECS tech pvt ltd.All rights Reserved</p>
</div>

ecommers_project/templates/header.html
{% load static %}
<header>
    <center>
<!--        click logo then go all prod -->
        <a href="{% url 'ecommers_app:allProdCat' %}"> </a><img src="{% static 'img/logo1.png' %}" alt="logimage" width="100px;" height="100px;">
    </center>
</header>

ecommers_project/templates/navbar.html
<!--navbar style-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'ecommers_app' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommers_app:allProdCat' %}">ALL PRODUCTS</a>
           {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="d-flex "  action="{% url 'search_app:SearchResult' %}" method="get" >
      {% csrf_token %}
      <input class="form-control me-2 " type="search" placeholder="Search" name="q" aria-label="Search" >
      <button class="btn btn-outline-success " type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
  </div>
</nav>
<!--end style-->

<!--<nav>-->
<!--    <ul>-->
<!--        <li>-->
<!--            <a href="{% url 'ecommers_app:allProdCat' %}">ALL PRODUCTS</a>-->
<!--        </li>-->
<!--        {% for cat in links %}-->
<!--        <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
<!--        {% endfor %}-->
<!--        <li>Your Cart()</li>-->
<!--    </ul>-->
<!--</nav>-->
<!--CREATE GET_URL IN MODELS-->

ecommers_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
         {{ kproduct.description|truncatewords:155 }}
{% endblock %}
{% block title %}
   {% if category %}
     {{ kproduct.name }} -ECS Store
   {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommers_app:allProdCat' %}"> HOME </a> | <a href="{{kproduct.category.get_url}}">{{kproduct.category}}</a>|{{kproduct.name}}</p>
    </div>
</div>
<div  class="containetr">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{kproduct.image.url}}" alt="{{kproduct.name}}" width="500px" height="350px">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title"><b>{{kproduct.name}}</b></h1>
            <p>${{kproduct.price}}</p>
                <p class="my_title"><b>Product Description</b></p>
            <p class="text-justify my_rod_text">{{kproduct.description}}</p>
            {% if kproduct.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' kproduct.id %}">Add to Cart</a>
            {% endif %}
        </div>
    </div>
</div>
    </div>
{% endblock %}

ecommers_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of products .
{% endblock %}
{% block title %}
 Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
<!--        here the product is the var_name of iterative variable -->
        {% for kproduct in products %}
          <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
             <div class="card text-center" style="min-width:18rem;">
                 <a href="{{kproduct.get_url}}"><img class="card-img-top my-image" src="{{kproduct.image.url}}" alt="{{kproduct.name}}" width="300px" height="200px"></a>
              <div class="card-body">
                 <h4>{{kproduct.name}}</h4>
                 <p>${{kproduct.price}}</p>
              </div>
             </div>
          </div>
         {% empty %}
           <div class="row mx-auto">
              <p class="text-center my_search_text">0 results found</p>
           </div>
        {% endfor %}
    </div>
</div>
{% endblock %}